;
; File generated by cc65 v 2.19 - Git c720c3c48
;
	.fopt		compiler,"cc65 v 2.19 - Git c720c3c48"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "mset.c", 6012, 1766602825
	.forceimport	__STARTUP__
	.dbg		sym, "ptr", "00", extern, "_ptr"
	.dbg		sym, "i", "00", extern, "_i"
	.dbg		sym, "j", "00", extern, "_j"
	.dbg		sym, "mouse_index", "00", extern, "_mouse_index"
	.dbg		sym, "mouse0", "00", extern, "_mouse0"
	.dbg		sym, "mouse1", "00", extern, "_mouse1"
	.dbg		sym, "mouse2", "00", extern, "_mouse2"
	.dbg		sym, "mouse3", "00", extern, "_mouse3"
	.dbg		sym, "mouse4", "00", extern, "_mouse4"
	.dbg		sym, "mouse_y", "00", extern, "_mouse_y"
	.dbg		sym, "mouse_x", "00", extern, "_mouse_x"
	.dbg		sym, "sprite_chr", "00", extern, "_sprite_chr"
	.dbg		sym, "ppu_send_addr", "00", extern, "_ppu_send_addr"
	.dbg		sym, "ppu_send_count", "00", extern, "_ppu_send_count"
	.dbg		sym, "ppu_send", "00", extern, "_ppu_send"
	.dbg		sym, "palette", "00", extern, "_palette"
	.dbg		sym, "oam", "00", extern, "_oam"
	.importzp	_ptr
	.importzp	_i
	.importzp	_j
	.importzp	_mouse_index
	.importzp	_mouse0
	.importzp	_mouse1
	.importzp	_mouse2
	.importzp	_mouse3
	.importzp	_mouse4
	.importzp	_mouse_y
	.importzp	_mouse_x
	.import		_sprite_chr
	.import		_mouse_sense
	.import		_input_setup
	.import		_input_poll
	.import		_ppu_latch
	.import		_ppu_load
	.import		_ppu_fill
	.import		_ppu_ctrl
	.import		_ppu_scroll_x
	.import		_ppu_scroll_y
	.import		_ppu_post
	.import		_ppu_send_addr
	.import		_ppu_send_count
	.import		_ppu_send
	.import		_palette
	.import		_oam
	.export		_cls
	.export		_mxl
	.export		_mxh
	.export		_myl
	.export		_myh
	.export		_mlh_reset
	.export		_line
	.export		_oam_pos
	.export		_add_sprite
	.export		_add_hex_sprite
	.export		_add_dec_sprite
	.export		_mouse_last
	.export		_mouse_new
	.export		_new_poll
	.export		_test
	.export		_main

.segment	"DATA"

_line:
	.byte	$00
_oam_pos:
	.byte	$00

.segment	"BSS"

_mxl:
	.res	1,$00
_mxh:
	.res	1,$00
_myl:
	.res	1,$00
_myh:
	.res	1,$00
_mouse_last:
	.res	1,$00
_mouse_new:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ cls (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_cls: near

	.dbg	func, "cls", "00", static, "_cls"

.segment	"CODE"

;
; ppu_latch(0x2000);
;
	.dbg	line, "mset.c", 106
	ldx     #$20
	lda     #$00
	jsr     _ppu_latch
;
; ppu_fill(0xFF,0x1000);
;
	.dbg	line, "mset.c", 107
	lda     #$FF
	jsr     pusha
	ldx     #$10
	lda     #$00
	jmp     _ppu_fill

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ mlh_reset (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_mlh_reset: near

	.dbg	func, "mlh_reset", "00", static, "_mlh_reset"

.segment	"CODE"

;
; mxl = 0;
;
	.dbg	line, "mset.c", 117
	lda     #$00
	sta     _mxl
;
; mxh = 0;
;
	.dbg	line, "mset.c", 118
	sta     _mxh
;
; myl = 0;
;
	.dbg	line, "mset.c", 119
	sta     _myl
;
; myh = 0;
;
	.dbg	line, "mset.c", 120
	sta     _myh
;
; }
;
	.dbg	line, "mset.c", 121
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ add_sprite (unsigned char x, unsigned char y, unsigned char tile)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_add_sprite: near

	.dbg	func, "add_sprite", "00", static, "_add_sprite"
	.dbg	sym, "x", "00", auto, 2
	.dbg	sym, "y", "00", auto, 1
	.dbg	sym, "tile", "00", auto, 0

.segment	"CODE"

;
; {
;
	.dbg	line, "mset.c", 127
	jsr     pusha
;
; oam[oam_pos+0] = y-1;
;
	.dbg	line, "mset.c", 128
	lda     _oam_pos
	clc
	adc     #<(_oam)
	sta     ptr1
	lda     #$00
	adc     #>(_oam)
	sta     ptr1+1
	ldy     #$01
	lda     (c_sp),y
	sec
	sbc     #$01
	dey
	sta     (ptr1),y
;
; oam[oam_pos+1] = tile;
;
	.dbg	line, "mset.c", 129
	ldx     #$00
	lda     _oam_pos
	jsr     incax1
	clc
	adc     #<(_oam)
	sta     ptr1
	txa
	adc     #>(_oam)
	sta     ptr1+1
	lda     (c_sp),y
	sta     (ptr1),y
;
; oam[oam_pos+2] = 0;
;
	.dbg	line, "mset.c", 130
	ldx     #$00
	lda     _oam_pos
	jsr     incax2
	clc
	adc     #<(_oam)
	sta     ptr1
	txa
	adc     #>(_oam)
	sta     ptr1+1
	tya
	sta     (ptr1),y
;
; oam[oam_pos+3] = x;
;
	.dbg	line, "mset.c", 131
	tax
	lda     _oam_pos
	jsr     incax3
	clc
	adc     #<(_oam)
	sta     ptr1
	txa
	adc     #>(_oam)
	sta     ptr1+1
	ldy     #$02
	lda     (c_sp),y
	ldy     #$00
	sta     (ptr1),y
;
; oam_pos += 4;
;
	.dbg	line, "mset.c", 132
	lda     #$04
	clc
	adc     _oam_pos
	sta     _oam_pos
;
; }
;
	.dbg	line, "mset.c", 133
	jmp     incsp3

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ add_hex_sprite (unsigned char x, unsigned char y, unsigned char value)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_add_hex_sprite: near

	.dbg	func, "add_hex_sprite", "00", static, "_add_hex_sprite"
	.dbg	sym, "x", "00", auto, 2
	.dbg	sym, "y", "00", auto, 1
	.dbg	sym, "value", "00", auto, 0

.segment	"CODE"

;
; {
;
	.dbg	line, "mset.c", 136
	jsr     pusha
;
; add_sprite(x,y,value>>4);
;
	.dbg	line, "mset.c", 137
	ldy     #$02
	lda     (c_sp),y
	jsr     pusha
	ldy     #$02
	lda     (c_sp),y
	jsr     pusha
	ldy     #$02
	lda     (c_sp),y
	lsr     a
	lsr     a
	lsr     a
	lsr     a
	jsr     _add_sprite
;
; add_sprite(x+8,y,value&0xF);
;
	.dbg	line, "mset.c", 138
	ldy     #$02
	lda     (c_sp),y
	clc
	adc     #$08
	jsr     pusha
	ldy     #$02
	lda     (c_sp),y
	jsr     pusha
	ldy     #$02
	lda     (c_sp),y
	and     #$0F
	jsr     _add_sprite
;
; }
;
	.dbg	line, "mset.c", 139
	jmp     incsp3

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ add_dec_sprite (unsigned char x, unsigned char y, signed char value)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_add_dec_sprite: near

	.dbg	func, "add_dec_sprite", "00", static, "_add_dec_sprite"
	.dbg	sym, "x", "00", auto, 2
	.dbg	sym, "y", "00", auto, 1
	.dbg	sym, "value", "00", auto, 0
	.dbg	sym, "sign", "00", auto, -1

.segment	"CODE"

;
; {
;
	.dbg	line, "mset.c", 142
	jsr     pusha
;
; uint8 sign = (value < 0) ? 1 : 0;
;
	.dbg	line, "mset.c", 143
	ldy     #$00
	lda     (c_sp),y
	asl     a
	tya
	bcc     L000F
	lda     #$01
L000F:	jsr     pusha
;
; if (sign) value = 0 - value;
;
	.dbg	line, "mset.c", 144
	ldy     #$00
	lda     (c_sp),y
	beq     L0005
	jsr     push0
	ldy     #$03
	lda     (c_sp),y
	bpl     L0006
	ldx     #$FF
L0006:	jsr     tossubax
	cmp     #$80
	ldy     #$01
	sta     (c_sp),y
;
; i = (uint8)value;
;
	.dbg	line, "mset.c", 160
L0005:	ldy     #$01
	lda     (c_sp),y
	sta     _i
;
; j = 0;
;
	.dbg	line, "mset.c", 161
	lda     #$00
	sta     _j
;
; if (i >= 100)
;
	.dbg	line, "mset.c", 162
	lda     _i
	cmp     #$64
	bcc     L0008
;
; j=1;
;
	.dbg	line, "mset.c", 164
	sty     _j
;
; i-=100;
;
	.dbg	line, "mset.c", 165
	lda     _i
	sec
	sbc     #$64
	sta     _i
;
; add_sprite(x,y,i%10); x -= 8;
;
	.dbg	line, "mset.c", 167
L0008:	ldy     #$03
	lda     (c_sp),y
	jsr     pusha
	ldy     #$03
	lda     (c_sp),y
	jsr     pusha
	lda     _i
	jsr     pusha0
	lda     #$0A
	jsr     tosumoda0
	jsr     _add_sprite
	ldy     #$03
	lda     (c_sp),y
	sec
	sbc     #$08
	sta     (c_sp),y
;
; if (i >= 10 || j > 0)
;
	.dbg	line, "mset.c", 168
	lda     _i
	cmp     #$0A
	bcs     L0010
	lda     _j
	beq     L0011
;
; i /= 10;
;
	.dbg	line, "mset.c", 170
L0010:	lda     _i
	jsr     pusha0
	lda     #$0A
	jsr     tosudiva0
	sta     _i
;
; add_sprite(x,y,i); x -= 8;
;
	.dbg	line, "mset.c", 171
	ldy     #$03
	lda     (c_sp),y
	jsr     pusha
	ldy     #$03
	lda     (c_sp),y
	jsr     pusha
	lda     _i
	jsr     _add_sprite
	ldy     #$03
	lda     (c_sp),y
	sec
	sbc     #$08
	sta     (c_sp),y
;
; if (j > 0)
;
	.dbg	line, "mset.c", 173
L0011:	lda     _j
	beq     L000C
;
; add_sprite(x,y,j); x -= 8;
;
	.dbg	line, "mset.c", 175
	lda     (c_sp),y
	jsr     pusha
	ldy     #$03
	lda     (c_sp),y
	jsr     pusha
	lda     _j
	jsr     _add_sprite
	ldy     #$03
	lda     (c_sp),y
	sec
	sbc     #$08
	sta     (c_sp),y
;
; if (sign) add_sprite(x,y,0x10);
;
	.dbg	line, "mset.c", 178
L000C:	ldy     #$00
	lda     (c_sp),y
	beq     L000D
	ldy     #$03
	lda     (c_sp),y
	jsr     pusha
	ldy     #$03
	lda     (c_sp),y
	jsr     pusha
	lda     #$10
	jsr     _add_sprite
;
; }
;
	.dbg	line, "mset.c", 179
L000D:	jmp     incsp4

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ new_poll (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_new_poll: near

	.dbg	func, "new_poll", "00", static, "_new_poll"

.segment	"CODE"

;
; input_poll();
;
	.dbg	line, "mset.c", 186
	jsr     _input_poll
;
; mouse_new = mouse1 & (mouse1 ^ mouse_last);
;
	.dbg	line, "mset.c", 187
	lda     _mouse1
	jsr     pusha0
	lda     _mouse1
	eor     _mouse_last
	jsr     tosanda0
	sta     _mouse_new
;
; mouse_last = mouse1;
;
	.dbg	line, "mset.c", 188
	lda     _mouse1
	sta     _mouse_last
;
; }
;
	.dbg	line, "mset.c", 189
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ test (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_test: near

	.dbg	func, "test", "00", static, "_test"

.segment	"CODE"

;
; cls();
;
	.dbg	line, "mset.c", 193
	jsr     _cls
;
; mlh_reset();
;
	.dbg	line, "mset.c", 194
	jsr     _mlh_reset
;
; for (i=0; i<32; i+=4)
;
	.dbg	line, "mset.c", 196
	lda     #$00
L002C:	sta     _i
	cmp     #$20
	bcs     L002D
;
; palette[i+0] = 0x0F;
;
	.dbg	line, "mset.c", 198
	lda     _i
	clc
	adc     #<(_palette)
	sta     ptr1
	lda     #$00
	adc     #>(_palette)
	sta     ptr1+1
	lda     #$0F
	ldy     #$00
	sta     (ptr1),y
;
; palette[i+1] = 0x00;
;
	.dbg	line, "mset.c", 199
	ldx     #$00
	lda     _i
	jsr     incax1
	clc
	adc     #<(_palette)
	sta     ptr1
	txa
	adc     #>(_palette)
	sta     ptr1+1
	tya
	sta     (ptr1),y
;
; palette[i+2] = 0x10;
;
	.dbg	line, "mset.c", 200
	tax
	lda     _i
	jsr     incax2
	clc
	adc     #<(_palette)
	sta     ptr1
	txa
	adc     #>(_palette)
	sta     ptr1+1
	lda     #$10
	sta     (ptr1),y
;
; palette[i+3] = 0x30;
;
	.dbg	line, "mset.c", 201
	ldx     #$00
	lda     _i
	jsr     incax3
	clc
	adc     #<(_palette)
	sta     ptr1
	txa
	adc     #>(_palette)
	sta     ptr1+1
	lda     #$30
	ldy     #$00
	sta     (ptr1),y
;
; for (i=0; i<32; i+=4)
;
	.dbg	line, "mset.c", 196
	lda     #$04
	clc
	adc     _i
	jmp     L002C
;
; palette[12+3] = 0x00; // grey background text
;
	.dbg	line, "mset.c", 203
L002D:	lda     #$00
	sta     _palette+15
;
; oam_pos = 0;
;
	.dbg	line, "mset.c", 207
L0006:	lda     #$00
L002F:	sta     _oam_pos
;
; add_sprite(125+mouse_x,117+mouse_y,0x27);
;
	.dbg	line, "mset.c", 209
	tax
	lda     _mouse_x
	bpl     L0009
	dex
L0009:	ldy     #$7D
	jsr     incaxy
	jsr     pusha
	ldx     #$00
	lda     _mouse_y
	bpl     L000A
	dex
L000A:	ldy     #$75
	jsr     incaxy
	jsr     pusha
	lda     #$27
	jsr     _add_sprite
;
; add_sprite(125,117,0x24);
;
	.dbg	line, "mset.c", 210
	lda     #$7D
	jsr     pusha
	lda     #$75
	jsr     pusha
	lda     #$24
	jsr     _add_sprite
;
; add_sprite((2+10)*8,(2+line)*8,0x11);
;
	.dbg	line, "mset.c", 212
	lda     #$60
	jsr     pusha
	lda     _line
	clc
	adc     #$02
	asl     a
	asl     a
	asl     a
	jsr     pusha
	lda     #$11
	jsr     _add_sprite
;
; ppu_send_addr = 0x2000 + 2 + ((2+line) * 32);
;
	.dbg	line, "mset.c", 213
	ldx     #$00
	lda     _line
	jsr     incax2
	jsr     aslax4
	jsr     aslax1
	sta     ptr1
	stx     ptr1+1
	lda     #$02
	clc
	adc     ptr1
	sta     _ppu_send_addr
	lda     #$20
	adc     ptr1+1
	sta     _ppu_send_addr+1
;
; ppu_send_count = 10;
;
	.dbg	line, "mset.c", 214
	lda     #$0A
	sta     _ppu_send_count
;
; ppu_send[0] = mouse0 >> 4;
;
	.dbg	line, "mset.c", 215
	lda     _mouse0
	lsr     a
	lsr     a
	lsr     a
	lsr     a
	sta     _ppu_send
;
; ppu_send[1] = mouse0 & 0xF;
;
	.dbg	line, "mset.c", 216
	lda     _mouse0
	and     #$0F
	sta     _ppu_send+1
;
; ppu_send[2] = mouse1 >> 4;
;
	.dbg	line, "mset.c", 217
	lda     _mouse1
	lsr     a
	lsr     a
	lsr     a
	lsr     a
	sta     _ppu_send+2
;
; ppu_send[3] = mouse1 & 0xF;
;
	.dbg	line, "mset.c", 218
	lda     _mouse1
	and     #$0F
	sta     _ppu_send+3
;
; ppu_send[4] = mouse2 >> 4;
;
	.dbg	line, "mset.c", 219
	lda     _mouse2
	lsr     a
	lsr     a
	lsr     a
	lsr     a
	sta     _ppu_send+4
;
; ppu_send[5] = mouse2 & 0xF;
;
	.dbg	line, "mset.c", 220
	lda     _mouse2
	and     #$0F
	sta     _ppu_send+5
;
; ppu_send[6] = mouse3 >> 4;
;
	.dbg	line, "mset.c", 221
	lda     _mouse3
	lsr     a
	lsr     a
	lsr     a
	lsr     a
	sta     _ppu_send+6
;
; ppu_send[7] = mouse3 & 0xF;
;
	.dbg	line, "mset.c", 222
	lda     _mouse3
	and     #$0F
	sta     _ppu_send+7
;
; ppu_send[8] = mouse4 >> 4;
;
	.dbg	line, "mset.c", 223
	lda     _mouse4
	lsr     a
	lsr     a
	lsr     a
	lsr     a
	sta     _ppu_send+8
;
; ppu_send[9] = mouse4 & 0xF;
;
	.dbg	line, "mset.c", 224
	lda     _mouse4
	and     #$0F
	sta     _ppu_send+9
;
; ++line; if (line >= 24) line = 0;
;
	.dbg	line, "mset.c", 225
	inc     _line
	lda     _line
	cmp     #$18
	lda     #$00
	bcc     L0031
	sta     _line
;
; for (i=0; i<10; ++i) ppu_send[i] ^= 0x30; // SNES grey
;
	.dbg	line, "mset.c", 226
L0031:	sta     _i
L0032:	lda     _i
	cmp     #$0A
	bcs     L0033
	lda     #<(_ppu_send)
	ldx     #>(_ppu_send)
	clc
	adc     _i
	bcc     L0010
	inx
L0010:	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	eor     #$30
	sta     (ptr1),y
	inc     _i
	jmp     L0032
;
; add_hex_sprite(20*8,2*8,mouse0);
;
	.dbg	line, "mset.c", 228
L0033:	lda     #$A0
	jsr     pusha
	lda     #$10
	jsr     pusha
	lda     _mouse0
	jsr     _add_hex_sprite
;
; add_hex_sprite(22*8,3*8,mouse1);
;
	.dbg	line, "mset.c", 229
	lda     #$B0
	jsr     pusha
	lda     #$18
	jsr     pusha
	lda     _mouse1
	jsr     _add_hex_sprite
;
; add_hex_sprite(24*8,3*8,mouse2);
;
	.dbg	line, "mset.c", 230
	lda     #$C0
	jsr     pusha
	lda     #$18
	jsr     pusha
	lda     _mouse2
	jsr     _add_hex_sprite
;
; add_hex_sprite(26*8,3*8,mouse3);
;
	.dbg	line, "mset.c", 231
	lda     #$D0
	jsr     pusha
	lda     #$18
	jsr     pusha
	lda     _mouse3
	jsr     _add_hex_sprite
;
; add_hex_sprite(28*8,2*8,mouse4);
;
	.dbg	line, "mset.c", 232
	lda     #$E0
	jsr     pusha
	lda     #$10
	jsr     pusha
	lda     _mouse4
	jsr     _add_hex_sprite
;
; add_sprite(20*8,4*8,mouse_index >= 4 ? 0x10 : mouse_index);
;
	.dbg	line, "mset.c", 233
	lda     #$A0
	jsr     pusha
	lda     #$20
	jsr     pusha
	lda     _mouse_index
	cmp     #$04
	bcc     L0034
	lda     #$10
	jmp     L0035
L0034:	lda     _mouse_index
L0035:	jsr     _add_sprite
;
; add_sprite(22*8,4*8,(mouse1&0x30)>>4);
;
	.dbg	line, "mset.c", 234
	lda     #$B0
	jsr     pusha
	lda     #$20
	jsr     pusha
	lda     _mouse1
	and     #$30
	lsr     a
	lsr     a
	lsr     a
	lsr     a
	jsr     _add_sprite
;
; if (mouse_x < mxl) mxl = mouse_x;
;
	.dbg	line, "mset.c", 236
	ldx     #$00
	lda     _mouse_x
	bpl     L0014
	dex
L0014:	jsr     pushax
	ldx     #$00
	lda     _mxl
	bpl     L0015
	dex
L0015:	jsr     tosicmp
	bpl     L0013
	lda     _mouse_x
	sta     _mxl
;
; if (mouse_x > mxh) mxh = mouse_x;
;
	.dbg	line, "mset.c", 237
L0013:	ldx     #$00
	lda     _mouse_x
	bpl     L0018
	dex
L0018:	jsr     pushax
	ldx     #$00
	lda     _mxh
	bpl     L0019
	dex
L0019:	jsr     tosicmp
	bmi     L0017
	beq     L0017
	lda     _mouse_x
	sta     _mxh
;
; if (mouse_y < myl) myl = mouse_y;
;
	.dbg	line, "mset.c", 238
L0017:	ldx     #$00
	lda     _mouse_y
	bpl     L001C
	dex
L001C:	jsr     pushax
	ldx     #$00
	lda     _myl
	bpl     L001D
	dex
L001D:	jsr     tosicmp
	bpl     L001B
	lda     _mouse_y
	sta     _myl
;
; if (mouse_y > myh) myh = mouse_y;
;
	.dbg	line, "mset.c", 239
L001B:	ldx     #$00
	lda     _mouse_y
	bpl     L0020
	dex
L0020:	jsr     pushax
	ldx     #$00
	lda     _myh
	bpl     L0021
	dex
L0021:	jsr     tosicmp
	bmi     L001F
	beq     L001F
	lda     _mouse_y
	sta     _myh
;
; add_dec_sprite(29*8,5*8,mxl);
;
	.dbg	line, "mset.c", 240
L001F:	lda     #$E8
	jsr     pusha
	lda     #$28
	jsr     pusha
	lda     _mxl
	jsr     _add_dec_sprite
;
; add_dec_sprite(29*8,6*8,mxh);
;
	.dbg	line, "mset.c", 241
	lda     #$E8
	jsr     pusha
	lda     #$30
	jsr     pusha
	lda     _mxh
	jsr     _add_dec_sprite
;
; add_dec_sprite(29*8,8*8,myl);
;
	.dbg	line, "mset.c", 242
	lda     #$E8
	jsr     pusha
	lda     #$40
	jsr     pusha
	lda     _myl
	jsr     _add_dec_sprite
;
; add_dec_sprite(29*8,9*8,myh);
;
	.dbg	line, "mset.c", 243
	lda     #$E8
	jsr     pusha
	lda     #$48
	jsr     pusha
	lda     _myh
	jsr     _add_dec_sprite
;
; while (oam_pos != 0)
;
	.dbg	line, "mset.c", 245
	jmp     L0029
;
; oam[oam_pos+0] = 0xF0;
;
	.dbg	line, "mset.c", 247
L0036:	lda     _oam_pos
	clc
	adc     #<(_oam)
	sta     ptr1
	lda     #$00
	adc     #>(_oam)
	sta     ptr1+1
	lda     #$F0
	ldy     #$00
	sta     (ptr1),y
;
; oam_pos += 4;
;
	.dbg	line, "mset.c", 248
	lda     #$04
	clc
	adc     _oam_pos
	sta     _oam_pos
;
; while (oam_pos != 0)
;
	.dbg	line, "mset.c", 245
L0029:	lda     _oam_pos
	bne     L0036
;
; ppu_post(POST_UPDATE);
;
	.dbg	line, "mset.c", 252
	lda     #$03
	jsr     _ppu_post
;
; new_poll();
;
	.dbg	line, "mset.c", 253
	jsr     _new_poll
;
; if (mouse_new & MOUSE_L)
;
	.dbg	line, "mset.c", 255
	lda     _mouse_new
	and     #$40
	beq     L0037
;
; mlh_reset();
;
	.dbg	line, "mset.c", 257
	jsr     _mlh_reset
;
; if (mouse_new & MOUSE_R)
;
	.dbg	line, "mset.c", 260
L0037:	lda     _mouse_new
	ldx     #$00
	and     #$80
	jeq     L002F
;
; mouse_sense();
;
	.dbg	line, "mset.c", 262
	jsr     _mouse_sense
;
; while (1)
;
	.dbg	line, "mset.c", 205
	jmp     L0006

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

	.dbg	func, "main", "00", static, "_main"

.segment	"CODE"

;
; input_setup();
;
	.dbg	line, "mset.c", 269
	jsr     _input_setup
;
; mouse_last = mouse1;
;
	.dbg	line, "mset.c", 270
	lda     _mouse1
	sta     _mouse_last
;
; ppu_latch(0x0000);
;
	.dbg	line, "mset.c", 272
	ldx     #$00
	txa
	jsr     _ppu_latch
;
; ppu_fill(0x00,8*1024);
;
	.dbg	line, "mset.c", 273
	lda     #$00
	jsr     pusha
	ldx     #$20
	jsr     _ppu_fill
;
; ptr = sprite_chr;
;
	.dbg	line, "mset.c", 275
	lda     #>(_sprite_chr)
	sta     _ptr+1
	lda     #<(_sprite_chr)
	sta     _ptr
;
; ppu_latch(0x0000);
;
	.dbg	line, "mset.c", 276
	ldx     #$00
	txa
	jsr     _ppu_latch
;
; ppu_load(SPRITE_CHR_SIZE);
;
	.dbg	line, "mset.c", 277
	ldx     #$04
	lda     #$00
	jsr     _ppu_load
;
; ppu_ctrl(0x00);
;
	.dbg	line, "mset.c", 279
	lda     #$00
	jsr     _ppu_ctrl
;
; ppu_scroll_x(0);
;
	.dbg	line, "mset.c", 281
	ldx     #$00
	txa
	jsr     _ppu_scroll_x
;
; ppu_scroll_y(0);
;
	.dbg	line, "mset.c", 282
	ldx     #$00
	txa
	jsr     _ppu_scroll_y
;
; test();
;
	.dbg	line, "mset.c", 283
	jmp     _test

	.dbg	line
.endproc

